before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

env:
- GUICE_VERSION=3.0 SCALA_VERSION_2_11=2.11.0 SCALA_VERSION_2_12=2.12.0
- GUICE_VERSION=4.2.0 SCALA_VERSION_2_11=2.11.12 SCALA_VERSION_2_12=2.12.4

jdk:
- openjdk8
- oraclejdk8
- oraclejdk9

language: scala

matrix:
  exclude:
  - env: GUICE_VERSION=3.0 SCALA_VERSION_2_11=2.11.0 SCALA_VERSION_2_12=2.12.0
    jdk: oraclejdk9

script: sbt "so test"
