---
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

dist: xenial

# Don't use slim or alpine images here - the SBT Wrapper runs a shell script which wouldn't always work then:
env:
  - COMPILE_IMAGE_TAG=11-jdk TEST_IMAGE_TAG=11-jdk
  - COMPILE_IMAGE_TAG=11-jdk TEST_IMAGE_TAG=13-jdk

install: ./docker-sbtx $COMPILE_IMAGE_TAG -no-colors +test:compile

language: minimal

# Run the build in Docker to shield it from changes in the Travis environment:
services:
  - docker

script: ./docker-sbtx $TEST_IMAGE_TAG -no-colors +test
