cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
env:
- GUICE_VERSION=3.0 PARADISE_VERSION=2.1.0
- GUICE_VERSION=4.1.0 PARADISE_VERSION=2.1.0
git:
  depth: 3
jdk: oraclejdk8
language: scala
scala:
- 2.11.0
- 2.12.0
