before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

dist: xenial

env:
  - SBT_IMAGE_TAG=sbt1.2.8-jdk8-alpine  GUICE_VERSION=3.0
  - SBT_IMAGE_TAG=sbt1.2.8-jdk11-alpine GUICE_VERSION=3.0
  - SBT_IMAGE_TAG=sbt1.2.8-jdk8-alpine  GUICE_VERSION=4.2.2
  - SBT_IMAGE_TAG=sbt1.2.8-jdk11-alpine GUICE_VERSION=4.2.2

language: java

services:
  - docker

script:
  - docker run
    --env GUICE_VERSION
    --interactive
    --rm
    --tty
    --volume $HOME/.ivy2:/root/.ivy2
    --volume $HOME/.sbt:/root/.sbt
    --volume $PWD:/work
    --workdir /work
    eed3si9n/sbt:sbt1.2.8-jdk11-alpine
    sbt +test:compile
    &&
    docker run
    --env GUICE_VERSION
    --interactive
    --rm
    --tty
    --volume $HOME/.ivy2:/root/.ivy2
    --volume $HOME/.sbt:/root/.sbt
    --volume $PWD:/work
    --workdir /work
    eed3si9n/sbt:$SBT_IMAGE_TAG
    sbt +test
