before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

env:
- GUICE_VERSION=3.0 SCALA_VERSION_2.11=2.11.0 SCALA_VERSION_2.12=2.12.0
- GUICE_VERSION=4.1.0 SCALA_VERSION_2.11=2.11.11 SCALA_VERSION_2.12=2.12.2

git:
  depth: 3

jdk:
- openjdk8
- oraclejdk8

language: scala

script: sbt "so test"

sudo: false
