before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

dist: trusty

env:
  - JDK_VERSION=openjdk8 GUICE_VERSION=3.0
  - JDK_VERSION=openjdk10 GUICE_VERSION=3.0
  - JDK_VERISON=openjdk8 GUICE_VERSION=4.2.2
  - JDK_VERSION=openjdk10 GUICE_VERSION=4.2.2

language: scala

before_script:
  - jdk_switcher use openjdk11
  - sbt -jvm-opts travis/jvmopts.compile +test:compile
  - jdk_switcher use $JDK_VERSION

script:
  - sbt -jvm-opts travis/jvmopts.test +test
