before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

dist: xenial

env:
  - COMPILE_IMAGE_TAG=11.0.2_2.12.8_1.2.8 TEST_IMAGE_TAG=8u212_2.12.8_1.2.8  GUICE_VERSION=3.0
  - COMPILE_IMAGE_TAG=11.0.2_2.12.8_1.2.8 TEST_IMAGE_TAG=11.0.2_2.12.8_1.2.8 GUICE_VERSION=3.0
  - COMPILE_IMAGE_TAG=11.0.2_2.12.8_1.2.8 TEST_IMAGE_TAG=8u212_2.12.8_1.2.8  GUICE_VERSION=4.2.2
  - COMPILE_IMAGE_TAG=11.0.2_2.12.8_1.2.8 TEST_IMAGE_TAG=11.0.2_2.12.8_1.2.8 GUICE_VERSION=4.2.2

language: minimal

services:
  - docker

script:
  - ./docker-build.sh $COMPILE_IMAGE_TAG $TEST_IMAGE_TAG
