before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

dist: xenial

env:
  - COMPILE_IMAGE_TAG=1.2.8-jdk9 TEST_IMAGE_TAG=1.2.8-jdk8  GUICE_VERSION=3.0
  - COMPILE_IMAGE_TAG=1.2.8-jdk9 TEST_IMAGE_TAG=1.2.8-jdk12 GUICE_VERSION=3.0
  - COMPILE_IMAGE_TAG=1.2.8-jdk9 TEST_IMAGE_TAG=1.2.8-jdk8  GUICE_VERSION=4.2.2
  - COMPILE_IMAGE_TAG=1.2.8-jdk9 TEST_IMAGE_TAG=1.2.8-jdk12 GUICE_VERSION=4.2.2

language: minimal

services:
  - docker

script:
  - ./docker-build.sh $COMPILE_IMAGE_TAG $TEST_IMAGE_TAG
