before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache

services:
  - docker

env:
  - SBT_IMAGE_TAG=sbt1.2.8-jdk8-alpine  GUICE_VERSION=3.0
  - SBT_IMAGE_TAG=sbt1.2.8-jdk11-alpine GUICE_VERSION=3.0
  - SBT_IMAGE_TAG=sbt1.2.8-jdk8-alpine  GUICE_VERSION=4.2.2
  - SBT_IMAGE_TAG=sbt1.2.8-jdk11-alpine GUICE_VERSION=4.2.2

before_script:
  - docker run
    --env GUICE_VERSION
    --interactive
    --rm
    --tty
    --volume $PWD:/work
    --volume $HOME/.ivy2:/root/.ivy2
    --workdir /work
    eed3si9n/sbt:sbt1.2.8-jdk11-alpine
    sbt +test:compile

script:
  - docker run
    --env GUICE_VERSION
    --interactive
    --rm
    --tty
    --volume $PWD:/work
    --volume $HOME/.ivy2:/root/.ivy2
    --workdir /work
    eed3si9n/sbt:$SBT_IMAGE_TAG
    sbt +test
