before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

env:
- GUICE_VERSION=3.0
- GUICE_VERSION=4.2.2

jdk:
- openjdk9
- openjdk11

language: scala

script: sbt +test
