before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

dist: trusty

env:
- GUICE_VERSION=3.0 SCALA_VERSION_2_11=2.11.0 SCALA_VERSION_2_12=2.12.0
- GUICE_VERSION=4.2.0 SCALA_VERSION_2_11=2.11.12 SCALA_VERSION_2_12=2.12.5

git:
  depth: 3

jdk:
- openjdk8
- oraclejdk8
- oraclejdk9

language: scala

script: sbt "so test"
