jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Compile with SBT
        run: sbt --batch +test:compile
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '8'
      - name: Test with SBT
        run: sbt --batch +test
name: test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
